[tools]
node = "lts"
flutter = "latest"
terraform = "latest"
rust = "latest"
usage = "latest"
python = "latest"
uv = "latest"
java = "17"
pnpm = "latest"
dotnet = "latest"
go = "latest"
"pipx:psf/black" = "latest"
"github:firebase/firebase-tools" = "latest"

[settings]
experimental = true
disable_hints = ["false"]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = []
