[tools]
node = "lts"
flutter = "latest"
fluttergen = "latest"
terraform = "latest"
direnv = "latest"
rust = "latest"
usage = "latest"
python = "latest"
uv = "latest"
java = "17"
pnpm = "latest"
dotnet = "latest"
go = "latest"
opencode = "latest"
act = "latest"
atuin = "latest"
balena = "latest"
boilerplate = "latest"
bun = "latest"
chezmoi = "latest"
infisical = "latest"
gitconfig = "latest"
github-cli = "latest"
ghalint = "latest"
tmux = "latest"
yazi = "latest"
lazygit = "latest"
lazydocker = "latest"
lazyjournal = "latest"
lazyssh = "latest"
sops = "latest"
neovim = "latest"
starship = "latest"
zoxide = "latest"
fzf = "latest"
eza = "latest"
ripgrep = "latest"
fd = "latest"
jq = "latest"
tree-sitter = "latest"
ollama = "latest"
carapace = "latest"
"pipx:psf/black" = "latest"
"github:firebase/firebase-tools" = "latest"

[settings]
experimental = true
disable_hints = ["false"]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = []

[shell_alias]
zshconfig = "nvim ~/.zshrc"
ohmyzsh = "nvim ~/.oh-my-zsh"
v = "nvim"
zsource = 'source ~/.zshrc'
gdu = 'gdu-go'

ls = "eza -l --icons=always -m -n -l"
l = "eza -l --icons=always -m -n -l -a"
ll = "eza -l --icons=always -m -n -l"

mkdir = 'mkdir -pv'

firebase = "firebase-tools"

dbb = "flutter clean && dart run build_runner build -d"
dbw = "flutter clean && dart run build_runner watch -d"
mbf = "mason make feature_brick --project_name $(cat pubspec.yaml | awk 'NR==1 {print; exit}' | awk '{print $2}') --name"

cea = "npx create-expo-app@latest"
cea-blank = "npx create-expo-app@latest --template blank-typescript"
